// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
	export interface GlobalComponents {
		IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
		IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
		IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
		IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
		IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
		TabBar: typeof import('./src/components/TabBar.vue')['default']
	}
}

export {}
